name: Push to GCR

on:
  push:
    branches:
      - dev

jobs:
  push_to_gcr:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: united-electron-414109
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY2 }}'
