name: Push to GCR

on:
  push:
    branches:
      - dev
    paths:
      - 'app/backend/**'
      - 'app/frontend/**'

jobs:
  push_to_gcr:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: united-electron-414109
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY2 }}'

      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2' 
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          # Check if frontend-image exists locally
          if docker images | grep -q "gcr.io/${{ env.GCP_PROJECT_ID }}/frontend"; then
              docker rmi gcr.io/${{ env.GCP_PROJECT_ID }}/frontend:${GITHUB_SHA:0:7}
          fi
          
          # Check if backend-image exists locally
          if docker images | grep -q "gcr.io/${{ env.GCP_PROJECT_ID }}/backend"; then
              docker rmi gcr.io/${{ env.GCP_PROJECT_ID }}/backend:${GITHUB_SHA:0:7}
          fi
          docker build -f frontend.Dockerfile -t gcr.io/${{ env.GCP_PROJECT_ID }}/frontend:${GITHUB_SHA:0:7} .
          docker build -f backend.Dockerfile -t gcr.io/${{ env.GCP_PROJECT_ID }}/backend:${GITHUB_SHA:0:7} .
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/frontend:${GITHUB_SHA:0:7}
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/backend:${GITHUB_SHA:0:7}
        working-directory: app