name: Push to GCR

on:
  push:
    branches:
      - dev

jobs:
  push_to_gcr:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: united-electron-414109
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY2 }}'

      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2' 
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker pull nginx:latest
          docker tag nginx:latest gcr.io/${{ env.GCP_PROJECT_ID }}/test-image:latest
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/test-image:latest
